name: Publish Artifacts

on:
  push:
    branches: [ "main" ] # Runs only when pushing to main branch

jobs:
  build:
    name: Build and Publish
    runs-on: macos-latest # macOS is required for Kotlin Multiplatform (iOS)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install GPG and Import Key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          brew install gpg
          echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secring.gpg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Configure Gradle Properties
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          cat <<EOF > gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          mavenCentralUsername=${MAVEN_CENTRAL_USERNAME}
          mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}
          signing.keyId=${SIGNING_KEY_ID}
          signing.password=${SIGNING_KEY_PASSWORD}
          signing.secretKeyRingFile=${HOME}/secring.gpg
          EOF

      - name: Setup Xcode (For KMP iOS Builds)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Clean and Build
        run: ./gradlew clean build --no-configuration-cache

      - name: Publish To Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache